field: 2cb07e17-ac9b-4b31-a6f2-6a4e5eaddadd
fieldLayouts:
  e828c0ba-d4a7-4e9b-83da-71b774642ed1:
    tabs:
      -
        elements:
          -
            fieldUid: 2c61b7dd-5913-4ec5-a983-d184c7615cf3
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8484b97-21cd-4231-b6ec-124181cc0ba6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2c61b7dd-5913-4ec5-a983-d184c7615cf3:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Enter the main text here.'
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c8484b97-21cd-4231-b6ec-124181cc0ba6:
    contentColumnType: text
    fieldGroup: null
    handle: table
    instructions: ''
    name: Table
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Number
                -
                  - handle
                  - number
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Description
                -
                  - handle
                  - description
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: text
name: Text
sortOrder: 1
